name: hackathon2_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  webview_flutter: ^4.4.2
  url_launcher: ^6.1.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  geolocator: ^10.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/